// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnhORJFTUu4gmy8nwJV14bI0GvQPkL28',
    appId: '1:954226101704:web:265037a079ae0b361084fd',
    messagingSenderId: '954226101704',
    projectId: 'hello-fluttter',
    authDomain: 'hello-fluttter.firebaseapp.com',
    storageBucket: 'hello-fluttter.firebasestorage.app',
    measurementId: 'G-4R8HRSFXVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9XoF_IaDs1QP__X9p0fhLzpmwoKpWDA',
    appId: '1:954226101704:android:7bde29064593c6971084fd',
    messagingSenderId: '954226101704',
    projectId: 'hello-fluttter',
    storageBucket: 'hello-fluttter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcu2OKE3w3nydfWP_n0ioR71ng9LFup4A',
    appId: '1:954226101704:ios:e3dd09a7fae632731084fd',
    messagingSenderId: '954226101704',
    projectId: 'hello-fluttter',
    storageBucket: 'hello-fluttter.firebasestorage.app',
    iosBundleId: 'com.example.propertyDealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcu2OKE3w3nydfWP_n0ioR71ng9LFup4A',
    appId: '1:954226101704:ios:e3dd09a7fae632731084fd',
    messagingSenderId: '954226101704',
    projectId: 'hello-fluttter',
    storageBucket: 'hello-fluttter.firebasestorage.app',
    iosBundleId: 'com.example.propertyDealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPnhORJFTUu4gmy8nwJV14bI0GvQPkL28',
    appId: '1:954226101704:web:2bbe306cec4978ee1084fd',
    messagingSenderId: '954226101704',
    projectId: 'hello-fluttter',
    authDomain: 'hello-fluttter.firebaseapp.com',
    storageBucket: 'hello-fluttter.firebasestorage.app',
    measurementId: 'G-PX7ZFLE69H',
  );
}
